### ISSUE TITLE
Failure in expression factorization

### ISSUE THREAD

**Issue by wence-** [coneoproject/COFFEE#110]
This is boiled down from a problem in thetis_adjoint.

```python
from coffee.factorizer import Factorizer

from coffee import base as ast

n1 = ast.Symbol("n1")
n2 = ast.Symbol("n2")
n3 = ast.Symbol("n3")
n4 = ast.Symbol("n4")
lvalue = ast.Div(ast.Sum(ast.Sum(n1, n1),
                         ast.Sum(n2, n2)),
                 n3)

stmt = ast.Incr(n4, lvalue)
fact = Factorizer(stmt)

fact.factorize(lambda x: False)
=>
Traceback (most recent call last):
  File "foo.py", line 16, in <module>
    fact.factorize(lambda x: False)
  File "/data/lmitche1/src/firedrake/src/COFFEE/coffee/factorizer.py", line 237, in factorize
    self._factorize(node, parent)
  File "/data/lmitche1/src/firedrake/src/COFFEE/coffee/factorizer.py", line 180, in _factorize
    self._factorize(n, node)
  File "/data/lmitche1/src/firedrake/src/COFFEE/coffee/factorizer.py", line 211, in _factorize
    factor = [t.factors_ast] if t.factors else [Symbol(1.0)]
  File "/data/lmitche1/src/firedrake/src/COFFEE/coffee/factorizer.py", line 60, in factors_ast
    return ast_make_expr(self.op, self.factors)
  File "/data/lmitche1/src/firedrake/src/COFFEE/coffee/utils.py", line 185, in ast_make_expr
    return _ast_make_bal_expr(nodes)
  File "/data/lmitche1/src/firedrake/src/COFFEE/coffee/utils.py", line 180, in _ast_make_bal_expr
    _ast_make_bal_expr(nodes[half:]))
TypeError: 'NoneType' object is not callable
```

**Comment by wence-** [comment]
Bisect blames: 5fcd9427c6f0

**Comment by wence-** [comment]
Even simpler:
```python
from coffee.factorizer import Factorizer
from coffee import base as ast

n1 = ast.Symbol("n1")
n2 = ast.Symbol("n2")
lvalue = ast.Sum(n1, n1)

stmt = ast.Incr(n2, lvalue)
fact = Factorizer(stmt)

fact.factorize(lambda x: False)
```

**Comment by wence-** [comment]
Closing, since this part of the technology has moved to tsfc.
